-- Rollback: คืน MAT_PRO_CODE และ MAT_WD_CODE กลับเป็น VARCHAR2(9)
-- ใช้เฉพาะเมื่อ data ทั้งหมดไม่เกิน 9 ตัวอักษร

ALTER TABLE MATERIAL_PROCUREMENT
    MODIFY (MAT_PRO_CODE VARCHAR2(9) NOT NULL);

ALTER TABLE MATERIAL_WITHDRAWN
    MODIFY (MAT_WD_CODE VARCHAR2(9) NOT NULL);
