-- MAT_PRO_METHOD: ตารางวิธีการจัดซื้อจัดจ้าง
-- ต้องรัน Script นี้ก่อนใช้งาน Dropdown วิธีการจัดซื้อจัดจ้างจาก Oracle
-- Primary Key: METHOD_ID (NUMBER), ชื่อวิธี: METHOD_NAME (VARCHAR2), IS_ACTIVE: 1=ใช้งาน 0=ปิด, SORT_ORDER: ลำดับแสดง

CREATE TABLE MAT_PRO_METHOD (
    METHOD_ID    NUMBER(3)     NOT NULL,
    METHOD_NAME  VARCHAR2(100) NOT NULL,
    IS_ACTIVE    NUMBER(1)     DEFAULT 1 NOT NULL,
    SORT_ORDER   NUMBER(3)     DEFAULT 0,
    CONSTRAINT pk_mat_pro_method PRIMARY KEY (METHOD_ID),
    CONSTRAINT chk_mat_pro_method_active CHECK (IS_ACTIVE IN (0, 1))
);

INSERT INTO MAT_PRO_METHOD (METHOD_ID, METHOD_NAME, IS_ACTIVE, SORT_ORDER) VALUES (1, 'เฉพาะเจาะจง',  1, 1);
INSERT INTO MAT_PRO_METHOD (METHOD_ID, METHOD_NAME, IS_ACTIVE, SORT_ORDER) VALUES (2, 'ประกวดราคา',   1, 2);
INSERT INTO MAT_PRO_METHOD (METHOD_ID, METHOD_NAME, IS_ACTIVE, SORT_ORDER) VALUES (3, 'คัดเลือก',     1, 3);
COMMIT;

-- ยืนยัน
SELECT METHOD_ID, METHOD_NAME, IS_ACTIVE, SORT_ORDER
FROM   MAT_PRO_METHOD
ORDER BY SORT_ORDER, METHOD_ID;
